name: Deploy WhatsAppni Bot

on:
  push:
    branches: [main]

env:
  DOCKER_IMAGE_NAME: whatsappnibot
  PROJECT_DIR: /home/whatsappni

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e  # Включаем строгий режим
            
            # Очищаем старые контейнеры
            echo "Очищаем старые контейнеры..."
            docker stop $DOCKER_IMAGE_NAME || true
            docker rm $DOCKER_IMAGE_NAME || true
            
            # Создаем рабочую директорию
            echo "Создаем рабочую директорию..."
            mkdir -p $PROJECT_DIR
            cd $PROJECT_DIR
            
            # Клонируем репозиторий
            echo "Клонируем репозиторий..."
            if [ ! -d ".git" ]; then
              git init
              git remote add origin https://github.com/nasimlat/whatsappni.git 
              git fetch --depth=1 origin ${{ github.ref }}
              git checkout -b ${{ github.ref_name }} origin/${{ github.ref_name }}
            else
              git fetch origin
              git reset --hard origin/${{ github.ref_name }}
            fi
            
            # Собираем Docker-образ
            echo "Собираем Docker-образ..."
            docker build -t $DOCKER_IMAGE_NAME .
            
            # Запускаем контейнер
            echo "Запускаем контейнер..."
            docker run -d \
              --name $DOCKER_IMAGE_NAME \
              -e BOT_TOKEN=${{ secrets.BOT_TOKEN }} \
              -e TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }} \
              $DOCKER_IMAGE_NAME