name: Deploy Telegram Bot

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest  # ОС для выполнения задач

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Клонируем репозиторий

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Установка Python

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt  # Установка зависимостей

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }} # Имя пользователя на сервере
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Остановите текущую службу бота
            systemctl stop telegram-bot || true

            # Обновите код на сервере
            cd /app  # Путь к папке с ботом на сервере
            git fetch origin
            git reset --hard origin/main

            # Установите зависимости
            pip3 install -r requirements.txt --no-cache-dir

            # Перезапустите службу
            systemctl start telegram-bot
