name: Deploy Telegram Bot

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt  # Для локальной проверки (необязательно)

      - name: Build and push Docker image
        run: |
          docker build -t telegram-bot .
          docker save telegram-bot > telegram-bot.tar

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Остановите и удалите старый контейнер
            docker stop telegram-bot || true
            docker rm telegram-bot || true

            # Перейдите в директорию проекта
            cd /root/bots/whatsappni # Путь к вашему проекту на сервере

            # Обновите код из репозитория
            git fetch origin
            git reset --hard origin/main

            # Загрузите и запустите новый контейнер
            docker load < telegram-bot.tar
            docker run -d \
              --name telegram-bot \
              -e BOT_TOKEN=${{ secrets.BOT_TOKEN }} \
              telegram-bot